travis:
  secure:
    BINSTAR_TOKEN: C2NLppNdiNdAvnrI1DNzRS1Gl1VzpEhGW2XItpeHD118axoH32Qi0/Xza6nMSsrhgLiOcTBsc5HSI/5RG5YJwtgWXQio4pSTmD/WBFII6mncbBGgFq/DD4DJYC+APuzpICfszK3D9kFWxkp11+idBjx7C0Ba6YBtsORl/aJvag5KiH0Zb320xTeOO2pTddx2BNderTd0az0RTjiuBsNI2nmTiYjQmuwK1ZR/MoVQlNYdNMPjA3XdM4nSu5bk7U8LQDcv3eossNYJIzLgvAQkdCTvTKhGWXDbo2fBxUNYWA3jCuiGlX/cLe9HQGuen1QSztWS4n188XLe2tlL1dfrVWd0nDFkFw3bF3BVfI68YPx08t6UMQQSXUtqf8WpsRzFBvVYIo9G+HOWjGN5KAGwYQZcWSIJ6pSoN0EJLy+O60ozT90vu63aHCxZbHZmSYzEEShe+j10aJ25p9fdZoYlrzgxpuHweatoM9DGSfzbTd0kSrlUvmlAscFj2JrfubUzKU/2FllVuNNcV4hIhS011Z+H6xZOZG7VsN5qBHNECZXeoxVppxuy/VBY7RRz0Vk3O22e+rZpoCrTXPIM06x3rR79R08DXKShNcTUUbIVdDHOwxw6T/5WftcIORWmyH0YsOgeA6tozPEv2eeibwVq9akrhiaSaK/hmiox0LrXDFc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
